<?php

namespace Database\Seeders;

use App\Services\Backend\Modules\CommonModule\CommonService;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ComplaintSeeder extends Seeder
{

    protected CommonService $common_service;

    public function __construct(CommonService $common_service)
    {
        $this->common_service = $common_service;
    }

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement("DELETE FROM complaints");
        DB::table("complaints")->insert([
            [
                "id" => "1",
                "title" => "Billing Discrepancy Issue",
                "description" => "Billing Discrepancy Issue",
                "category" => "billing",
                "priority" => "low",
                "status" => "resolved",
                "image" => null,
                "created_by" => "2",
                "submission_date" => "2024-10-28",
                "resolved_at" => "2024-10-29",
                "time_taken" => 86400,
                "day_taken" => 1,
                "created_at" => Carbon::now()->subMonth(1),
                "updated_at" => Carbon::now()->subMonth(1),
            ],
            [
                "id" => "2",
                "title" => "Delayed Delivery Complaint",
                "description" => "Delayed Delivery Complaint",
                "category" => "service_issue",
                "priority" => "medium",
                "status" => "in_progress",
                "image" => null,
                "created_by" => "3",
                "submission_date" => "2024-10-25",
                "resolved_at" => "2024-10-27",
                "time_taken" => 172800,
                "day_taken" => 2,
                "created_at" => Carbon::now()->subMonth(1),
                "updated_at" => Carbon::now()->subMonth(1),
            ],
            [
                "id" => "3",
                "title" => "Product Quality Issue",
                "description" => "Product Quality Issue",
                "category" => "product_issue",
                "priority" => "high",
                "status" => "open",
                "image" => null,
                "created_by" => "4",
                "submission_date" => "2024-09-28",
                "resolved_at" => "2024-09-30",
                "time_taken" => 172800,
                "day_taken" => 2,
                "created_at" => Carbon::now()->subMonth(2),
                "updated_at" => Carbon::now()->subMonth(2),
            ],
            [
                "id" => "4",
                "title" => "Incorrect Item Received",
                "description" => "Incorrect Item Received",
                "category" => "product_issue",
                "priority" => "medium",
                "status" => "resolved",
                "image" => null,
                "created_by" => "1",
                "submission_date" => "2024-10-01",
                "resolved_at" => "2024-10-03",
                "time_taken" => 172800,
                "day_taken" => 2,
                "created_at" => Carbon::now()->subMonth(2),
                "updated_at" => Carbon::now()->subMonth(2),
            ],
            [
                "id" => "5",
                "title" => "Refund Not Processed",
                "description" => "Refund Not Processed",
                "category" => "billing",
                "priority" => "high",
                "status" => "closed",
                "image" => null,
                "created_by" => "2",
                "submission_date" => "2024-10-10",
                "resolved_at" => "2024-10-15",
                "time_taken" => 432000,
                "day_taken" => 5,
                "created_at" => Carbon::now()->subMonth(1),
                "updated_at" => Carbon::now()->subMonth(1),
            ],
            [
                "id" => "6",
                "title" => "Account Suspension Issue",
                "description" => "Account Suspension Issue",
                "category" => "service_issue",
                "priority" => "high",
                "status" => "open",
                "image" => null,
                "created_by" => "3",
                "submission_date" => "2024-09-20",
                "resolved_at" => "2024-09-25",
                "time_taken" => 432000,
                "day_taken" => 5,
                "created_at" => Carbon::now()->subMonth(3),
                "updated_at" => Carbon::now()->subMonth(3),
            ],
            [
                "id" => "7",
                "title" => "Technical Support Needed",
                "description" => "Technical Support Needed",
                "category" => "service_issue",
                "priority" => "low",
                "status" => "in_progress",
                "image" => null,
                "created_by" => "4",
                "submission_date" => "2024-09-22",
                "resolved_at" => "2024-09-23",
                "time_taken" => 86400,
                "day_taken" => 1,
                "created_at" => Carbon::now()->subMonth(3),
                "updated_at" => Carbon::now()->subMonth(3),
            ],
            [
                "id" => "8",
                "title" => "Payment Failure Issue",
                "description" => "Payment Failure Issue",
                "category" => "billing",
                "priority" => "medium",
                "status" => "resolved",
                "image" => null,
                "created_by" => "1",
                "submission_date" => "2024-10-12",
                "resolved_at" => "2024-10-13",
                "time_taken" => 86400,
                "day_taken" => 1,
                "created_at" => Carbon::now()->subMonth(2),
                "updated_at" => Carbon::now()->subMonth(2),
            ],
            [
                "id" => "9",
                "title" => "Product Defect Issue",
                "description" => "Product Defect Issue",
                "category" => "product_issue",
                "priority" => "high",
                "status" => "resolved",
                "image" => null,
                "created_by" => "2",
                "submission_date" => "2024-09-18",
                "resolved_at" => "2024-09-22",
                "time_taken" => 345600,
                "day_taken" => 4,
                "created_at" => Carbon::now()->subMonth(3),
                "updated_at" => Carbon::now()->subMonth(3),
            ],
            [
                "id" => "10",
                "title" => "Late Order Delivery",
                "description" => "Late Order Delivery",
                "category" => "service_issue",
                "priority" => "medium",
                "status" => "open",
                "image" => null,
                "created_by" => "3",
                "submission_date" => "2024-09-10",
                "resolved_at" => "2024-09-11",
                "time_taken" => 86400,
                "day_taken" => 1,
                "created_at" => Carbon::now()->subMonth(3),
                "updated_at" => Carbon::now()->subMonth(3),
            ],
            [
                "id" => "11",
                "title" => "Subscription Cancellation Issue",
                "description" => "Subscription Cancellation Issue",
                "category" => "billing",
                "priority" => "low",
                "status" => "closed",
                "image" => null,
                "created_by" => "4",
                "submission_date" => "2024-10-05",
                "resolved_at" => "2024-10-07",
                "time_taken" => 172800,
                "day_taken" => 2,
                "created_at" => Carbon::now()->subMonth(1),
                "updated_at" => Carbon::now()->subMonth(1),
            ],
            [
                "id" => "12",
                "title" => "Product Replacement Needed",
                "description" => "Product Replacement Needed",
                "category" => "product_issue",
                "priority" => "medium",
                "status" => "resolved",
                "image" => null,
                "created_by" => "1",
                "submission_date" => "2024-09-12",
                "resolved_at" => "2024-09-14",
                "time_taken" => 172800,
                "day_taken" => 2,
                "created_at" => Carbon::now()->subMonth(2),
                "updated_at" => Carbon::now()->subMonth(2),
            ],
            [
                "id" => "13",
                "title" => "Account Recovery Issue",
                "description" => "Account Recovery Issue",
                "category" => "service_issue",
                "priority" => "high",
                "status" => "resolved",
                "image" => null,
                "created_by" => "2",
                "submission_date" => "2024-10-15",
                "resolved_at" => "2024-10-17",
                "time_taken" => 172800,
                "day_taken" => 2,
                "created_at" => Carbon::now()->subMonth(1),
                "updated_at" => Carbon::now()->subMonth(1),
            ],
            //... Add remaining records up to 20.
        ]);
        DB::table("complaints")->insert([
            [
                "id" => "14",
                "title" => "Incorrect Billing Amount",
                "description" => "Discrepancy in the billed amount and the expected charge.",
                "category" => "billing",
                "priority" => "medium",
                "status" => "open",
                "image" => null,
                "created_by" => "1",
                "submission_date" => "2024-10-15",
                "resolved_at" => "2024-10-16",
                "time_taken" => 86400,
                "day_taken" => 1,
                "created_at" => Carbon::now()->subMonth(1),
                "updated_at" => Carbon::now()->subMonth(1),
            ],
            [
                "id" => "15",
                "title" => "Payment Reversal Delay",
                "description" => "Delayed response for payment reversal after cancellation.",
                "category" => "billing",
                "priority" => "high",
                "status" => "in_progress",
                "image" => null,
                "created_by" => "2",
                "submission_date" => "2024-10-20",
                "resolved_at" => "2024-10-22",
                "time_taken" => 172800,
                "day_taken" => 2,
                "created_at" => Carbon::now()->subMonth(1),
                "updated_at" => Carbon::now()->subMonth(1),
            ],
            [
                "id" => "16",
                "title" => "Shipping Address Update Issue",
                "description" => "Unable to update shipping address on profile.",
                "category" => "service_issue",
                "priority" => "medium",
                "status" => "closed",
                "image" => null,
                "created_by" => "3",
                "submission_date" => "2024-09-10",
                "resolved_at" => "2024-09-12",
                "time_taken" => 172800,
                "day_taken" => 2,
                "created_at" => Carbon::now()->subMonth(3),
                "updated_at" => Carbon::now()->subMonth(3),
            ],
            [
                "id" => "17",
                "title" => "App Performance Slowdown",
                "description" => "Experiencing lag while using the mobile app.",
                "category" => "service_issue",
                "priority" => "low",
                "status" => "resolved",
                "image" => null,
                "created_by" => "4",
                "submission_date" => "2024-09-15",
                "resolved_at" => "2024-09-18",
                "time_taken" => 259200,
                "day_taken" => 3,
                "created_at" => Carbon::now()->subMonth(2),
                "updated_at" => Carbon::now()->subMonth(2),
            ],
            [
                "id" => "18",
                "title" => "Login Access Issue",
                "description" => "Unable to log in despite correct credentials.",
                "category" => "service_issue",
                "priority" => "high",
                "status" => "resolved",
                "image" => null,
                "created_by" => "1",
                "submission_date" => "2024-10-10",
                "resolved_at" => "2024-10-11",
                "time_taken" => 86400,
                "day_taken" => 1,
                "created_at" => Carbon::now()->subMonth(1),
                "updated_at" => Carbon::now()->subMonth(1),
            ],
            [
                "id" => "19",
                "title" => "Damaged Product Received",
                "description" => "Product received with visible physical damage.",
                "category" => "product_issue",
                "priority" => "high",
                "status" => "open",
                "image" => null,
                "created_by" => "2",
                "submission_date" => "2024-10-17",
                "resolved_at" => "2024-10-20",
                "time_taken" => 259200,
                "day_taken" => 3,
                "created_at" => Carbon::now()->subMonth(1),
                "updated_at" => Carbon::now()->subMonth(1),
            ],
            [
                "id" => "20",
                "title" => "Incorrect Order Quantity",
                "description" => "Order received with an incorrect quantity of items.",
                "category" => "product_issue",
                "priority" => "medium",
                "status" => "resolved",
                "image" => null,
                "created_by" => "3",
                "submission_date" => "2024-09-25",
                "resolved_at" => "2024-09-28",
                "time_taken" => 259200,
                "day_taken" => 3,
                "created_at" => Carbon::now()->subMonth(2),
                "updated_at" => Carbon::now()->subMonth(2),
            ]
        ]);
    }
}
